<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //1. 改变对象的状态
        // let p = new Promise((resolve, reject) => {
        //     // resolve();
        //     // reject();
        //     // throw '有点问题';
        //     // console.log(a);
        // });

        // console.log(p);

        //2. 为 promise 对象指定多个成功或失败的回调
        // let p = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         reject('error');
        //     }, 1000);
        // });

        // // //指定回调
        // p.then(value => {
        //     console.log(value);
        // }, reason => {
        //     console.error(reason);
        // });

        // p.then(value => {
        //     alert(value);
        // }, reason => {
        //     alert(reason);
        // });

        //3. 改变 promise 状态和指定回调函数谁先谁后?
        //      resolve          then
        // 都可以

        //4. promise.then()返回的新promise的结果状态由什么决定?
        // let p = new Promise((resolve ,reject) => {
        //     resolve('ok');
        // });

        // const result = p.then(value => {
        //     // console.log(value);
        //     //1. 抛出错误
        //     // throw 123;
        //     //2. 返回值不是 promise 对象
        //     // return 'abc';
        //     //3. 返回值是 promise 对象
        //     return new Promise((resolve,reject) => {
        //         // resolve('success');
        //         reject('error');
        //     });
        // }, reason => {

        // })

        // console.log(result);

        // 5. promise 如何串连多个操作任务?  promise 的链式调用
        // let p = new Promise((resolve, reject) => {
        //     reject('error');
        // });

        // p.then(value => {
        //     console.log(value);
        // }, reason => {
        //     console.error(reason);
        // }).then(value => {
        //     console.log(111);
        //     return new Promise((resolve, reject) => {
        //         reject(333);
        //     })
        // }, reason => {
        //     console.error(222);
        // }).then(value => {
        //     console.log(444);
        // }, reason =>{
        //     console.error(555);
        // })

        //6. promise异常传透?
        new Promise((resolve, reject) => {
            resolve('ok');
            // reject('error');
        }).then(value => {
            console.log(value);// ok 
            throw 'oh no';
        }).then(value => {
            console.log(value);// undefined
        }).catch(reason => {
            console.error(reason);
        });

    </script>
</body>
</html>